name: music_app
description: Une application musicale basée sur TheAudioDB API.
publish_to: 'none' # Retire cette ligne si vous souhaitez publier sur pub.dev

version: 1.0.0+1

# Ajout de la contrainte SDK manquante
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.1
  
  # Network
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Code generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icons/
    
# Fonts
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic